### ISSUE TITLE
do you have video tutorials, and do you have videos when you publish them?

### ISSUE THREAD

**Issue by dlsofree** [akumanomi1988/VideoNews#1]
do you have video tutorials, and do you have videos when you publish them?

**Comment by akumanomi1988** [comment]
if you configure all right, the video will be uploaded to youtube.

you can see the results in my youtube channel https://www.youtube.com/@Cronista.Global

let me 2 - 3 days and i will make a better tutorial with images

**Comment by akumanomi1988** [comment]
for the moment, here you are a explanation of the configuration:
To configure and run the **VideoNews** project, including both the YouTube API integration and the Telegram bot, here’s a detailed step-by-step guide:

### 1. **Environment Setup (Python 3.10)**
   - Ensure **Python 3.10** is installed on your system. You can download it from the [official Python site](https://www.python.org/downloads/release/python-3100/).
   - Create a virtual environment for the project to isolate dependencies:
     ```bash
     python3.10 -m venv venv
     source venv/bin/activate
     ```
   - Install the necessary dependencies using the command:
     ```bash
     pip install -r requirements.txt
     ```

### 2. **Google Cloud Console: YouTube API Setup**
   To allow the application to upload videos to YouTube, you need to set up the **YouTube Data API v3**:
   
   - Go to [Google Cloud Console](https://console.cloud.google.com/) and create a new project.
   - Navigate to **APIs & Services** → **Library**, search for “YouTube Data API v3,” and enable it.
   - Next, go to **Credentials** → **Create Credentials** → **OAuth 2.0 Client IDs**, and select **Desktop App** as the application type.
   - Download the OAuth 2.0 credentials JSON file. You’ll need it to authenticate your application with YouTube.
   
### 3. **Configuration of the Project**
   - In the cloned repository, locate the `settings.example.json` file and rename it to `settings.json`.
   - Inside `settings.json`, update the following sections:
     - **YouTube API**: Add the `client_id` and `client_secret` from the OAuth 2.0 credentials file.
     - **ElevenLabs API** (if used): Enter the necessary keys for text-to-speech processing (if required).
     - **Telegram Bot**: Add the bot token, which you will get in the next step.

### 4. **Telegram Bot Setup**
   - Create a Telegram bot by messaging [BotFather](https://t.me/BotFather).
   - Once created, BotFather will provide you with an API token. This token should be added to your `settings.json` under the **Telegram** section.
   
   Your `settings.json` should now include both YouTube API credentials and the Telegram bot token.

### 5. **Running the Project**
   - Once your environment and configuration files are set up, you can run the project using:
     ```bash
     python main.py
     ```
   - This will start both the YouTube upload functionality and the Telegram bot. The bot will allow you to interact with the project via Telegram.

### 6. **OAuth Authorization (YouTube API)**
   The first time you attempt to upload a video to YouTube, the script will prompt you to complete an OAuth 2.0 flow:
   - A browser window will open, asking you to authorize the application to access your YouTube account.
   - After authorization, the application will generate and store a token for subsequent uploads without requiring re-authorization.

### 7. **Testing and Usage**
   - Once the setup is complete, test the upload functionality by using the script to convert news articles into videos and upload them to YouTube.
   - Use the Telegram bot to trigger these actions remotely and manage the process.

Following these steps will ensure your project is configured correctly for both YouTube uploads and Telegram bot functionality using Python 3.10 in a virtual environment.

Let me know if you need further clarifications on any part of the setup!

**Comment by akumanomi1988** [comment]
> do you have video tutorials, and do you have videos when you publish them?

Was my response helpful to you?
If you have any questions, you can contact me in the following Telegram channel: [Join the VideoNews Community on Telegram](https://t.me/VideoNewsCommunity)
